config/routes.rb
Wifi::Application.routes.draw do

  resources :internets
  

end

app/models/internet.rb
class Internet < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/internets_controller.rb
class InternetsController < ApplicationController
	before_action :set_internet, only:[ :show, :edit, :update, :destroy]


	def index
		@internet = Internet.all
	end

	def new
		@internet  = Internet.new
	
	end

	def create
		@internet= Internet.new(internet_params)

		if @internet.save
			redirect_to internets_path
		else
			redirect_to new_internet_path
		end
		
	end

	def show
		
	end

	def edit
	end

	def update
	
		if @internet.update_attributes(internet_params)
			redirect_to internets_path
		end
	end
	 
	def destroy
	
		@internet.destroy
		redirect_to internets_path
	end

	def internet_params
		params.require(:internet).permit(:name, :speed, :amount)
	end

	def set_internet
		@internet=Internet.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/internet_helper.rb
module InternetHelper
end

app/helpers/internets_helper.rb
module InternetsHelper
end

app/views/internets/edit.html.erb
<%= form_for  @internet do | f | %>

<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :speed %>
<%= f.text_field :speed %>

<%= f.label :amount %>
<%= f.text_field :amount %>

<%= f.submit :update %>
<% end %>

<%= link_to 'Show', internet_path %>
<%= link_to 'Back', internets_path %>

app/views/internets/index.html.erb
<h1> Listing internets </h1>

<table>
	<thead>
		<tr>
			<th>name </th>
			<th>speed</th>
			<th>amount</th>
			<th></th>
			<th></th>
			<th></th>
		</tr>	
	</thead>	


	<tbody>
		<% @internet.each do | f | %>
		<tr>
			<td><%= f.name %></td>
			<td><%= f.speed %></td>
			<td><%= f.amount %></td>
			<td><%= link_to 'Show', f %></td>
			<td><%= link_to 'Edit', edit_internet_path(f) %></td>
			<td><%= link_to 'Destroy', f, method: :delete, data:{confirm: 'Are you sure?'} %></td>
		</tr>
		<% end %>
		
	</tbody>
</table>

<br>


<%= link_to 'New Internet', new_internet_path %>

app/views/internets/new.html.erb
<%= form_for  @internet do | f | %>

<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :speed %>
<%= f.text_field :speed %>

<%= f.label :amount %>
<%= f.text_field :amount %>

<%= f.submit :create %>

<% end %>

app/views/internets/show.html.erb
<p>
<strong>Interenet name:</strong>
<%= @internet.name %>
</p>

<p>
<strong>Speed:</strong>
<%= @internet.speed %>
</p>

<p>
<strong>Amount:</strong>
<%= @internet.amount %>
</p>

<%=link_to 'Edit', edit_internet_path(@internet) %>
<%=link_to 'Back', internets_path %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wifi</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>

<body background ="/4.jpg">

<%= yield %>

</body>
</html>